"""Observed text must beat generated text, everywhere it is used.

WHY THIS EXISTS
    ``conferences`` had no description column. The only prose a conference
    carried was ``enriched_description``, generated by an LLM from the
    conference's NAME — a prompt whose own instruction was to write "likely
    covers" / "typically focuses on".

    That guess was the first and largest part of the embedded blob, the
    whole of what the LLM judge reasoned about, and the source of the
    few-shot calibration examples. So the matcher's strongest signal, and
    every veto, rested on a description of an event that nobody had read.

    The real text was on disk the whole time — the scraper stores each page,
    and extraction read it for dates and CFP links, then dropped the prose.

    These tests pin the preference order that fixes it. They matter most in
    the direction that is easy to regress: falling back to the generated
    text is correct when there is nothing else, and wrong the moment there
    is.
"""

from __future__ import annotations

from app.db.models import Conference
from app.services.conferences import conference_embed_text


def _conf(**kw) -> Conference:
    base = dict(name="ExampleConf 2026", topics=[], cfp_topics_of_interest=[])
    base.update(kw)
    return Conference(**base)


def test_the_pages_own_words_are_used_when_present():
    c = _conf(
        description="A community meetup on vLLM inference and llm-d routing.",
        enriched_description="An annual conference that likely covers AI topics.",
    )
    text = conference_embed_text(c)
    assert "vLLM inference and llm-d routing" in text
    assert "likely covers" not in text, (
        "generated text must not be embedded alongside the real thing — "
        "it dilutes the vector with prose we wrote ourselves"
    )


def test_generated_text_is_still_the_fallback():
    """Enrichment keeps exactly one job: rows with no page to read, such as
    a name-only feed entry. Removing the fallback would regress those to a
    14-word blob that scores near zero."""
    c = _conf(description=None, enriched_description="An annual conference on MLOps.")
    assert "An annual conference on MLOps." in conference_embed_text(c)


def test_a_conference_with_neither_still_produces_its_structural_fields():
    c = _conf(description=None, enriched_description=None, location_city="Berlin")
    text = conference_embed_text(c)
    assert "ExampleConf 2026" in text
    assert "Berlin" in text


def test_the_judge_reads_the_real_description_and_hashes_it():
    """Two separate failures guarded here.

    The judge must reason about the page's words, since a veto is the
    strongest thing the system does to a conference.

    And ``judge_input_hash`` must include the field. If it did not, a
    conference that gained a real description would keep serving the
    cached verdict computed from the generated one — the cache would hide
    precisely the improvement this change exists to deliver.
    """
    from app.services.matcher import compute_judge_input_hash

    generated_only = _conf(description=None, enriched_description="Guessed prose.")
    with_real = _conf(description="Actual prose from the page.",
                      enriched_description="Guessed prose.")

    h1 = compute_judge_input_hash(
        conference=generated_only, pillars=[], operator_profile="acme", calibration=None
    )
    h2 = compute_judge_input_hash(
        conference=with_real, pillars=[], operator_profile="acme", calibration=None
    )
    assert h1 != h2, "gaining a real description must invalidate the cached verdict"


def test_extraction_schema_can_carry_a_description_and_event_kind():
    """Both are recovered from the page the extractor is already reading,
    so they cost no extra LLM call."""
    from app.services.extraction import ExtractedConference

    e = ExtractedConference(
        name="KubeCon Europe 2026",
        description="The Cloud Native Computing Foundation's flagship event.",
        event_kind="grassroot",
    )
    assert e.description.startswith("The Cloud Native")
    assert e.event_kind == "grassroot"


def test_an_unrecognised_event_kind_does_not_discard_the_conference():
    """Losing a whole conference because the model wrote 'summit' where we
    expect one of five enum values would be a bad trade."""
    from app.services.extraction import ExtractedConference

    e = ExtractedConference(name="Some Event 2026", event_kind="summit")
    assert e.event_kind is None
    assert e.name == "Some Event 2026"


def test_event_kind_is_normalised_not_rejected_on_formatting():
    from app.services.extraction import ExtractedConference

    assert ExtractedConference(
        name="A Dev Day 2026", event_kind="Developer-Day"
    ).event_kind == "developer_day"


def test_extractor_kinds_are_exactly_the_ones_the_database_accepts():
    """Derived, not restated — so the extractor cannot drift into
    producing a value the CHECK constraint will reject."""
    from app.schemas import EVENT_KINDS
    from app.services.extraction import ExtractedConference

    for kind in EVENT_KINDS:
        assert ExtractedConference(name="X 2026", event_kind=kind).event_kind == kind
