import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import { queryClient } from "@/lib/query-client";
import { routeTree } from "./routeTree.gen";

import "@/styles/index.css";

// Router. The route tree is generated by @tanstack/router-plugin at build
// time from the files under src/routes/. The generated file is gitignored;
// the dev server + build regenerate it on demand.
const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  scrollRestoration: true,
  // Context propagated to every route's loader — currently empty; we'll
  // add the QueryClient when first route uses it (plan 09+).
  context: {},
});

// Register the router type for end-to-end type safety on links + params.
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootEl = document.getElementById("root");
if (!rootEl) {
  throw new Error("Root element #root not found in index.html");
}

createRoot(rootEl).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
      {import.meta.env.DEV ? <ReactQueryDevtools initialIsOpen={false} /> : null}
    </QueryClientProvider>
  </StrictMode>,
);
