apiVersion: v1
kind: Service
metadata:
  name: {{ include "scout.fullname" . }}-api
  labels:
    {{- include "scout.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  {{- if .Values.oauth.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.oauth.tlsSecretName | default "scout-api-tls" }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "scout.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    {{- if .Values.oauth.enabled }}
    - name: oauth
      port: 8443
      targetPort: oauth
      protocol: TCP
    {{- end }}
