"""Conferences get a real description, extracted rather than invented.

``conferences`` had no description column at all. The only prose a
conference carried was ``enriched_description``, generated by
services/enrichment.py from name + topics + city — a prompt whose own
instruction was to write "likely covers" / "typically focuses on".

That generated text is the first and largest part of the blob the matcher
embeds (services/conference_text.py), the whole of what the LLM judge
reasons about (matcher/judge.py:214), and the source of the few-shot
calibration examples. So the strongest signal in the system, and every
veto, rested on a guess about the event rather than anything the event
had said about itself.

The real text was already on disk. services/scraper/fetch.py stores each
page as a RawPage, and extraction read it to recover dates, location and
CFP links — then dropped the prose. This column plus a ``description``
field on the extraction schema keeps it. No extra LLM call: the page is
already being read.

Nullable, no backfill. A NULL here is honest — it means we have not
re-extracted that page yet — and ``conference_embed_text`` falls back to
``enriched_description``, so nothing regresses while rows catch up.
Re-running extraction (or the enrich-and-match task) fills it in.

Revision ID: 20260727_0900
Revises: 20260726_1600
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20260727_0900"
down_revision = "20260726_1600"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "conferences",
        sa.Column("description", sa.Text(), nullable=True),
        schema="app",
    )


def downgrade() -> None:
    op.drop_column("conferences", "description", schema="app")
