import createClient from "openapi-fetch";

// Typed API client. The `paths` type is generated by `pnpm gen:api` from
// the api's OpenAPI schema (apps/api/openapi.json) — landing once we have
// CRUD endpoints in plan 09. Until then this is unparameterized and the
// types act like `any` on responses.
//
// Same-origin in production (the api serves the SPA from /static), so the
// empty baseUrl is correct. In dev the Vite proxy (vite.config.ts) forwards
// /api/* to the api container.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Paths = any; // replaced by `paths` from `./api-types` once gen:api runs

export const api = createClient<Paths>({
  baseUrl: "",
});

// Convenience helpers — both add a structured-error toast on failure.
// (Toast UI lands per-feature in plan 09.)
//
// For now we leave thin wrappers; real call sites land alongside their routes.
